# MAIN base
baseURL = "https://knowthychoice.in/"
languageCode = "en-us"
title = "KTC | Know Thy Choice"
theme = "apsho"

# Navigation Bar
[[menu.main]]
    name = "Programs"
    url = "#"
    weight = 1
[[menu.main]]
    name = "Career Exploration Lab"
    url = "/experienceship"
    parent = "Programs"
    weight = 1
[[menu.main]]
    name = "KTC Talks"
    url = "/ktctalks"
    parent = "Programs"
    weight = 2
[[menu.main]]
    name = "Counselling"
    url = "/counselling"
    parent = "Programs"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
[[menu.main]]
    name = "Blogs"
    url = "/blog"
    weight = 3

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Terms & Conditions"
    url = "/tnc"
    weight = 2
[[menu.sitemap]]
    name = "Privacy Policy"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Refund Policy"
    url = "/refund"
    weight = 4
[[menu.sitemap]]
    name = "Contact Us"
    url = "/contact"
    weight = 5

# Footer Address
[params.address]
address = "Bengaluru, India"
email = "hello@knowthychoice.in"
phone = "+91 874 595 6961"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/profile.php?id=100089246206640"
instagram = "https://www.instagram.com/knowthychoice/"
linkedin = "https://www.linkedin.com/company/knowthychoice/"

[params]

# Header
logo = "images/logo.png"
formspreeURL = "https://formspree.io/mknyovwz"
googleAnalytics = "G-251ESPDTK1"

# Footer
footerTitle = "Get the latest updates"
copyright1 = "All right reserved"
copyright2 = "Copyright Â© KTC {year} "

#contact
email = "shipra@knowthychoice.in"